// <auto-generated />
using System;
using DataSharedLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataSharedLibrary.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241022130840_AddMoreFields")]
    partial class AddMoreFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("DataSharedLibrary.ChapterContent", b =>
                {
                    b.Property<string>("ChapterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IndexChapter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .HasColumnType("TEXT");

                    b.HasKey("ChapterId");

                    b.HasIndex("BookId");

                    b.ToTable("ChapterContents");
                });

            modelBuilder.Entity("DataSharedLibrary.ChapterDetailContent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChapterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Index")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.ToTable("ChapterDetailContents");
                });

            modelBuilder.Entity("DataSharedLibrary.CurrentReader", b =>
                {
                    b.Property<string>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentChapter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentLine")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentPosition")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookId");

                    b.ToTable("CurrentReader");
                });

            modelBuilder.Entity("DataSharedLibrary.NovelContent", b =>
                {
                    b.Property<string>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageBase64")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxChapterCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortDesc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .HasColumnType("TEXT");

                    b.HasKey("BookId");

                    b.ToTable("NovelContents");
                });

            modelBuilder.Entity("DataSharedLibrary.ChapterContent", b =>
                {
                    b.HasOne("DataSharedLibrary.NovelContent", "NovelContent")
                        .WithMany("Chapters")
                        .HasForeignKey("BookId");

                    b.Navigation("NovelContent");
                });

            modelBuilder.Entity("DataSharedLibrary.ChapterDetailContent", b =>
                {
                    b.HasOne("DataSharedLibrary.ChapterContent", "ChapterContent")
                        .WithMany("ChapterDetailContents")
                        .HasForeignKey("ChapterId");

                    b.Navigation("ChapterContent");
                });

            modelBuilder.Entity("DataSharedLibrary.ChapterContent", b =>
                {
                    b.Navigation("ChapterDetailContents");
                });

            modelBuilder.Entity("DataSharedLibrary.NovelContent", b =>
                {
                    b.Navigation("Chapters");
                });
#pragma warning restore 612, 618
        }
    }
}
