// <auto-generated />
using System;
using DataSharedLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataSharedLibrary.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241009080312_InitModel")]
    partial class InitModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("DataSharedLibrary.ChapterContent", b =>
                {
                    b.Property<string>("ChapterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IndexChapter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NovelContentBookId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .HasColumnType("TEXT");

                    b.HasKey("ChapterId");

                    b.HasIndex("NovelContentBookId");

                    b.ToTable("ChapterContents");
                });

            modelBuilder.Entity("DataSharedLibrary.ChapterDetailContent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChapterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Index")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ChapterDetailContents");
                });

            modelBuilder.Entity("DataSharedLibrary.NovelContent", b =>
                {
                    b.Property<string>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageBase64")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxChapterCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .HasColumnType("TEXT");

                    b.HasKey("BookId");

                    b.ToTable("NovelContents");
                });

            modelBuilder.Entity("DataSharedLibrary.ChapterContent", b =>
                {
                    b.HasOne("DataSharedLibrary.NovelContent", null)
                        .WithMany("Chapters")
                        .HasForeignKey("NovelContentBookId");
                });

            modelBuilder.Entity("DataSharedLibrary.NovelContent", b =>
                {
                    b.Navigation("Chapters");
                });
#pragma warning restore 612, 618
        }
    }
}
